server:
  port: 8081

spring:
  application:
    name: reserve-service

  kafka:
    bootstrap-servers: localhost:9092

    consumer:
      group-id: store-reserve-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"
        spring.json.type.mapping: >
          reserveRequestEvent:com.max.reserve.event.reserve.ReserveRequestEvent

    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.type.mapping: >
          reserveResponseEvent:com.max.reserve.event.reserve.ReserveResponseEvent
        enable.idempotence: true
        acks: all
        retries: 3
        max.in.flight.requests.per.connection: 1

  datasource:
    url: jdbc:postgresql://localhost:5432/petDB
    username: bestuser
    password: bestuser
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true

logging:
  level:
    com.max.reserve: DEBUG
    org.springframework.web: INFO
  file:
