server:
  port: 8081

spring:
  application:
    name: reserve-service
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: reserve-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"

  datasource:
    url: jdbc:postgresql://localhost:5432/petDB
    username: bestuser
    password: bestuser
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  cache:
    type: redis
    redis:
      time-to-live: 300000    
      cache-null-values: false 
      key-prefix: "reserve:"   
      use-key-prefix: true   
  redis:
    host: localhost
    port: 6379
    database: 0               
    timeout: 2000ms           
    lettuce:
      pool:
        max-active: 8         
        max-idle: 8           
        min-idle: 2 

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true

logging:
  level:
    com.max.reserve: DEBUG
    org.springframework.web: INFO
    org.springframework.data.redis: DEBUG
  file:
