server:
  port: 8080

spring:

  application:
    name: store-app

  kafka:
    bootstrap-servers: localhost:9092

    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.type.mapping: >
          productInfoRequestEvent:com.max.store.event.productInfo.ProductInfoRequestEvent,
          reserveRequestEvent:com.max.store.event.reserve.ReserveRequestEvent
        enable.idempotence: true
        acks: all
        retries: 3
        max.in.flight.requests.per.connection: 1

    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"
        spring.json.type.mapping: >
          productInfoResponseEvent:com.max.store.event.productInfo.ProductInfoResponseEvent,
          reserveResponseEvent:com.max.store.event.reserve.ReserveResponseEvent

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true

logging:
  level:
    com.max.store: DEBUG
    org.springframework.web: INFO
    org.springframework.kafka: DEBUG
