server:
  port: 8080

spring:
  application:
    name: store-app

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true

logging:
  level:
    com.max.store: DEBUG
    org.springframework.web: INFO
  file:
